services:
  db:
    image: postgres:17.4
    container_name: actorfreq_db
    restart: always
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - actorfreq
    healthcheck:
      test: ["CMD", "sh", "-c", "pg_isready -U $ACTORFREQ_DB_USER -d $ACTORFREQ_DB_NAME -h $ACTORFREQ_DB_HOST"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s

  app:
    build: .
    container_name: actorfreq
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    networks:
      - actorfreq

volumes:
  pgdata: {}

networks:
  actorfreq:
